name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    name: ${{ matrix.os.name }} ${{ matrix.python }} ${{ matrix.qt }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            runs-on: windows-latest
        python: [3.6, 3.7, 3.8]
        qt: [5.14.0, 5.14.1, 5.14.2, 5.15.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: install python dependencies
        run: |
          pip install --upgrade pip
          pip install pyqt5 --only-binary pyqt5
          pip install pyside2 --only-binary pyside2
      - name: Install Qt ${{ matrix.qt }}
        uses: jurplel/install-qt-action@v2.7.2
        with:
          version: ${{ matrix.qt }}
          dir: "${{ github.workspace }}/qt/"
      - name: install
        run: python setup.py install
      - name: testing
        run: python main.py
        